services:
  ss14-watchdog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ss14-watchdog
    ports:
      - "1212:1212/tcp"
      - "1212:1212/udp"
      - "8010:8080/tcp"
    volumes:
      - ss14_data:/ss14
      - ./appsettings.yml:/ss14/appsettings.yml:ro
      - ./server_config.toml:/ss14/instances/test/config.toml:ro
      
    restart: unless-stopped

volumes:
  ss14_data: